/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Bus.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube072.geometry} material={materials.RED} />
      <mesh geometry={nodes.Cube072_1.geometry} material={materials.GLASS} />
      <mesh geometry={nodes.Cube072_2.geometry} material={materials.CROM} />
      <mesh geometry={nodes.Cube072_3.geometry} material={materials['YELLOW LIGHT']} />
      <mesh geometry={nodes.Cube072_4.geometry} material={materials.PLATE} />
      <mesh geometry={nodes.Cube072_5.geometry} material={materials.BLACK} />
      <mesh geometry={nodes.Cube072_6.geometry} material={materials['WHITE LIGHT']} />
      <mesh geometry={nodes.Cube072_7.geometry} material={materials['RED LIGHT']} />
      <mesh geometry={nodes.Cube072_8.geometry} material={materials.TIRES} />
    </group>
  )
}

useGLTF.preload('/Bus.glb')
