import '../../globals.css'
import type { Metadata } from 'next'
import Sidebar from './components/Sidebar'
import Navbar from './components/Navbar'

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-black'>
        <Navbar />
        {children}
      </body>
    </html>
  )
}