import '../../globals.css'
import type { Metadata } from 'next'
import Navbar from './home/components/Navbar'

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='overflow-x-hidden'>
        <div className='flex fixed justify-center w-screen h-[120px] pointer-events-none items-center z-[1001] overflow-x-hidden'>
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  )
}