import '../../../globals.css'
import type { Metadata } from 'next'
import Sidebar from '../components/Sidebar'

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <div className='bg-black'>
        <Sidebar />
        {children}
      </div>
  )
}